---

- hosts: bigips
  gather_facts: False
  remote_user: root
  tasks:
    - name: check bigips be reachable
      ping:
      
    - name: collect bigip partitions
      bigip_device_info:
        gather_subset:
          - partitions
        provider:
          user: admin
          server: "{{ inventory_hostname }}"
          password: "{{ admin_password }}"
          validate_certs: False
      register: partitions

    - name: show all partitions
      debug: var=partitions.partitions

    - name: remove objects under partitions
      file: path=/config/partitions/{{ item.name }} state=absent
      with_items: "{{partitions.partitions}}"
    
    - name: executing tmsh load sys config
      shell: tmsh load sys config

    - name: delete partitions
      bigip_partition:
        name: "{{item.name}}"
        state: absent
        provider:
          user: admin
          server: "{{ inventory_hostname }}"
          password: "{{ admin_password }}"
          validate_certs: False
      with_items: "{{partitions.partitions}}"
      when: item.name != "Common"
