---

- name: set timestamp variable
  shell: date +%s
  register: test_timestamp

- name: set neutron resource names
  set_fact:
    subnet: "{{ test_subnet }}"
    loadbalancer: lb-{{ test_timestamp.stdout }}
    listener: ls-{{ test_timestamp.stdout }}
    pool: pl-{{ test_timestamp.stdout }}
    member: mb-{{ test_timestamp.stdout }}
    l7policy: l7-{{ test_timestamp.stdout }}

- name: "smoking test: create lbaasv2 resources"
  shell: |
    source {{ openrc }} && {{ item }} && bash /tmp/scripts/wait_assert_lb_active.sh {{ loadbalancer }}
  with_items:
    - neutron lbaas-loadbalancer-create --name {{ loadbalancer }} {{ subnet }}
    - neutron lbaas-pool-create --name {{ pool }} --loadbalancer {{ loadbalancer }} --lb-algorithm ROUND_ROBIN --protocol HTTP
    - neutron lbaas-listener-create --name {{ listener }} --loadbalancer {{ loadbalancer }} --protocol HTTP --protocol-port 80
    - neutron lbaas-member-create --name {{ member }} --subnet {{ subnet }} --address 1.1.1.1 --protocol-port 80 {{ pool }}

- name: "TODO: check resources created on bigips"
  shell: echo "todo."
  run_once: True

- name: "smoking test: delete lbaasv2 resources"
  shell: |
    source {{ openrc }} && {{ item }} && sleep 3
  with_items:
    - neutron lbaas-member-delete {{ member }} {{ pool }}
    - neutron lbaas-pool-delete {{ pool }}
    - neutron lbaas-listener-delete {{ listener }}
    - neutron lbaas-loadbalancer-delete {{ loadbalancer }}