
- name: "{{ testcasename }}: get vip address for test"
  shell: |
    source {{ openrc }} && \
      neutron lbaas-loadbalancer-show {{ loadbalancer }} --format value --column vip_address
  register: vip_address
- debug: var=vip_address.stdout

- name: "{{ testcasename }}: get resource ids"
  shell: |
    source {{ openrc }} && {{ item }} --format value --column id
  register: resource_ids
  with_items:
    - neutron lbaas-loadbalancer-show {{ loadbalancer }}
    - neutron lbaas-pool-show {{ pool }}
    - neutron lbaas-listener-show {{ listener }}
    - neutron lbaas-healthmonitor-show {{ healthmonitor }}
    - neutron lbaas-member-list {{ pool }}
    - openstack project show $OS_PROJECT_NAME

- set_fact:
    loadbalancer_id: "{{resource_ids.results[0].stdout}}"
    pool_id: "{{resource_ids.results[1].stdout}}"
    listener_id: "{{resource_ids.results[2].stdout}}"
    healthmonitor_id: "{{resource_ids.results[3].stdout}}"
    member_ids: "{{resource_ids.results[4].stdout_lines}}"
    project_id: "{{resource_ids.results[5].stdout}}"

- debug: msg="{{ item }}"
  with_items:
    - "project_id:{{project_id}}"
    - "loadbalancer_id: {{ loadbalancer_id }}"
    - "pool_id: {{pool_id}}"
    - "listener_id: {{listener_id}}"
    - "healthmonitor_id: {{healthmonitor_id}}"
    - "member_ids: {{member_ids}}"

- name: collect bigip device info
  bigip_device_info:
    gather_subset:
      # - system-info
      - partitions
      # - provision-info
      # - interfaces
      # - client-ssl-profiles
      - ltm-pools
      - virtual-servers
      # - vlans
      # - nodes
      - virtual-addresses
      # - profiles
      # - devices
      # - http-profiles
      - monitors
    provider:
      user: admin
      server: "{{ item }}"
      password: "{{ hostvars[item].admin_password }}"
      validate_certs: False
  register: bigip_infos
  with_items: "{{ groups['bigips'] }}"
  delegate_to: localhost

- name: assert resources are created on bigips
  assert:
    that:
      - "'{{project_id}}' in '{{item.partitions | map(attribute='name') | list | join(' ') }}'"
      - "'{{loadbalancer_id}}' in '{{item.virtual_addresses | map(attribute='name') | list | join(' ') }}'"
      - "'{{listener_id}}' in '{{item.virtual_servers | map(attribute='name') | list | join(' ') }}'"
      - "'{{pool_id}}' in '{{item.ltm_pools | map(attribute='name') | list | join(' ') }}'"
  with_items: "{{bigip_infos.results}}"
  loop_control:
    label: "{{ item.item }}"
  no_log: yes
