---

- name: "{{ testcasename }}: create loadbalancer"
  shell: |
    source {{ openrc }} && neutron lbaas-loadbalancer-create --name {{ loadbalancer }} {{ subnet }}

- name: "{{ testcasename }}: create lbaasv2 resources"
  shell: |
    source {{ openrc }} && bash /tmp/scripts/wait_assert_lb_active.sh {{ loadbalancer }} && {{ item }}
  with_items:
    - neutron lbaas-pool-create --name {{ pool }} --loadbalancer {{ loadbalancer }} --lb-algorithm ROUND_ROBIN --protocol {{ pool_protocol }}
    - neutron lbaas-listener-create --name {{ listener }} --loadbalancer {{ loadbalancer }} --default-pool {{ pool }} --protocol {{ listener_protocol }} --protocol-port {{ listener_tcpport }} {{ listener_additional_options }}
    - neutron lbaas-healthmonitor-create --name {{ healthmonitor }} --delay 15 --timeout 15 --max-retries 5 --type {{ healthmonitor_protocol }} --pool {{ pool }}

- name: "{{ testcasename }}: create members under pool {{ pool }}"
  shell: |
    source {{ openrc }} && \
      bash /tmp/scripts/wait_assert_lb_active.sh {{ loadbalancer }} && \
      neutron lbaas-member-create --subnet {{ hostvars[item].subnet }} --address {{ item }} --protocol-port {{ tcpport }} {{ pool }}
  with_items:
    - "{{ hostvars[inventory_hostname]['groups']['backend_servers'] }}"
  when: test_env == 'lab'

- name: "{{ testcasename }}: get vip address for test"
  shell: |
    source {{ openrc }} && \
      neutron lbaas-loadbalancer-show {{ loadbalancer }} --format value --column vip_address
  register: vip_address
- debug: var=vip_address.stdout
